### ISSUE TITLE
New defaults for WPPF

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#1025]
@saransh13 -- I'm wondering if we should consider new default values for the instrumental parameters in WPPF.  The synchrotron CeO2, perhaps (tiff and yaml config attached).  Since we don't have export yet, here are the params:

![image](https://user-images.githubusercontent.com/1154130/132585643-af11f04c-0ccc-4b0b-82a8-2427f94589ed.png)

Seems like as 'generic' of PV parameters as we might get?

instrument config:

```
beam:
  energy: 80.725
  vector:
    azimuth: 90.0
    polar_angle: 90.0
detectors:
  GE:
    buffer:
    - 2
    - 2
    distortion:
      function_name: GE_41RT
      parameters:
      - -1.3831557917356484e-05
      - -6.722570188929893e-05
      - -0.0005190176705337566
      - 2.0
      - 4.0
      - 2.0
    pixels:
      columns: 2048
      rows: 2048
      size:
      - 0.2
      - 0.2
    saturation_level: 14000.0
    transform:
      tilt:
      - 0.0005694301846452315
      - -0.003172068857113122
      - 9.031366591899936e-07
      translation:
      - -1.4489082444363395
      - -3.23337663559735
      - -1050.7447282636172
id: instrument
oscillation_stage:
  chi: 0.0
  translation:
  - 0.0
  - 0.0
  - 0.0
```
[CeO2_single_GE.zip](https://github.com/HEXRD/hexrdgui/files/7131816/CeO2_single_GE.zip)
