### ISSUE TITLE
ERROR: find-orientations based on selected hkls

### ISSUE THREAD

**Issue by minety** [HEXRD/hexrdgui#1297]
<img width="1510" alt="image" src="https://user-images.githubusercontent.com/19909710/194481113-df2e9eed-7195-4407-9a6c-8b2795317c58.png">

Hi Joel, @joelvbernier 

I have no problem of indexing on the GUI version with selected hkls, but I have to trial and error on HPC using CLI version. I got the error above, I tried with many forms of inputs in YAML file, it never worked. This took me several days already. I think it would be better just to ask. It would be very appreciated if you can help me with this.

My yaml input file for find-orientations was:

```yaml
analysis_name: Test_sample_findori_seeds_0p8_t100_95pct # defaults to analysis

## working directory defaults to current working directory
## all relative paths specified herein are assumed to be in the working_dir
## any files not in working_dir should be specified with an absolute path
working_dir: /home/ytian37/scratch/Hurley/Test_0907/

multiprocessing: all # "all", or "half", or -1 means all but one, defaults to -1

material:
  definitions: SOLEIL_materials_221003.h5
  active: aquartz
  dmin: 1 # defaults to 1.0 angstrom
  tth_width: 0.3 # defaults to 0.25 degrees
  min_sfac_ratio: 0.05 # min percentage of max |F|^2 to exclude; default None

image_series:
  format: frame-cache
  data:
    - file: ottowa_15_diff1bis_10_w_omega_95pct_bg.npz
      args: {}
      panel: GE  # must match detector key


instrument: SOLEIL_sample_detector_20221003.yml

find_orientations:
  orientation_maps:
    # A file name must be specified. If it doesn't exist, one will be created
    file: null

    threshold: 100  #find_orientations
    bin_frames: 1 # defaults to 1

    # "all", or a list of hkl orders used to find orientations
    # defaults to all orders listed in the material definition
    active_hkls: [0,1,2,3,4,5,6]

  # either search full quaternion grid, or seed search based on sparse
  # orientation maps.  For input search space:
  #
  # use_quaternion_grid: some/file/name
  #
  # otherwise defaults to seeded search:
  seed_search: # this section is ignored if use_quaternion_grid is defined
    hkl_seeds: [3, 5] # hkls ids to use, must be defined for seeded search
    fiber_step: 0.5 # degrees, defaults to ome tolerance
    # Method selection:
    #   Now 3 choices: label (the original), 'blob_dog', and 'blob_log'
    #   Each has its own parameter names, examples below.
    #
    method:
      label:
        filter_radius: 4
        threshold: 1 # defaults to 1
    #
    # method:
    #   blob_dog:
    #     min_sigma: 0.5
    #     max_sigma: 5
    #     sigma_ratio: 1.6
    #     threshold: 0.01
    #     overlap: 0.1
    #
    # method:
    #   blob_log:
    #     min_sigma: 0.5
    #     max_sigma: 5
    #     num_sigma: 10
    #     threshold: 0.01
    #     overlap: 0.1
  # this is the on-map threshold using in the scoring
  # defaults to 1
  threshold: 1 #scoring?

  omega:
    tolerance: 0.2  # in degrees, defaults to 2x ome step

    # specify the branch cut, in degrees. The range must be 360 degrees.
    # defaults to full 360 starting at the first omega value in imageseries.
    # !!! THIS OPTION IS DEPRECATED.
    # period: [0, 360]

  eta:
    tolerance: 1  # in degrees, defaults to 2x ome step
    mask: 5  # degrees, mask angles close to ome rotation axis, defaults to 5

  clustering:
    # algorithm choices are
    #   sph-dbscan
    #   ort-dbscn
    #   dbscan <default>
    #   fclusterdata; this is a fallback and won't work for large problems
    radius: 0.3 # misorientation search range
    completeness: 0.8 # completeness threshold
    algorithm: dbscan


analysis_name: Test_sample_findori_seeds_0p8_t100_95pct # defaults to analysis

image_series:
  format: frame-cache
  data:
    - file: ottowa_15_diff1bis_10_w_omega_95pct_bg.npz
      args: {}
      panel: GE  # must match detector key

fit_grains:
  do_fit: true # if false, extracts grains but doesn't fit. defaults to true

  estimate: Test_sample_findori_seeds_0p8_t100_95pct/grains.out

  npdiv: 2 # number of polar pixel grid subdivisions, defaults to 2

  threshold: 10

  tolerance:
    tth: [0.25, 0.25] # tolerance lists must be identical length
    eta: [2.0, 1.0]
    omega: [2.0, 1.0]

  refit: [2, 1.1]

  tth_max: 9.344  # true, false, or a non-negative value, defaults to true
```
