### ISSUE TITLE
New LLNL Instruments

### ISSUE THREAD

**Issue by bnmajor** [HEXRD/hexrdgui#1318]
In order to add additional instruments to the LLNL Import tool we will need the following for each new instrument:
- In the [HEXRD resources](https://github.com/HEXRD/hexrd/tree/master/hexrd/resources) folder:
  - A text file describing each of the boundaries needed for cropping (in Cartesian coordinates)
  - A reference config file with appropriate defaults in the format `{instrument}_reference_config.yml`. If the user has not opted to load their own instrument config this is what will be used after the cropping has all been applied and the final images have been reloaded.
- In the [HEXRDGUI calibration resources](https://github.com/HEXRD/hexrdgui/tree/master/hexrd/ui/resources/calibration):
  - A default config file in the format `default_{instrument}_config.yml`. This is essentially copied from the `{instrument}_reference_config.yml` file but slimmed down and only including a single detector named `default` (no matter the instrument) where the columns/rows should match the original image size. This is what is used when the initial, un-cropped image is loaded and only requires the following keys:
    ```
    beam:
      energy:
      vector:
    detectors:
      default:
        pixels:
          columns:
          rows:
          size:
        transform:
          tilt:
          translation:
    oscillation_stage:
      chi:
      translation:
    ```
