### ISSUE TITLE
Add UI for grain fitting

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#375]
#363 adds UI for indexing. UI should be added as well for the grain fitting.

As of #400, grain fitting is ran automatically after indexing is complete. We now
just need to create a dialog around [here](https://github.com/HEXRD/hexrdgui/blob/1556de632910c2ace7c27ff06933e2f0143aa999/hexrd/ui/indexing/run.py#L103-L107) so the user can set grain fitting options,
and we need to add some visualization for it.

The options that the user will choose will look like the following:
```yaml
  # if false, extracts grains but doesn't fit. defaults to true
  do_fit: true

  # Can be set to the previous grain fitting output, to start with that output. 
  # estimate: null  

  # number of polar pixel grid subdivisions, defaults to 2
  npdiv: 4 

  # This could possibly be the same as the threshold from the indexing,
  # which is determined by the minimum value of the color map in the indexing.
  threshold: 25

  # These lists need to be identical in length. Basically, it goes from
  # "high tolerance" to "low tolerance". The user might want 2 tolerances each, as is
  # done here. Or they might want 3, 4, etc.
  tolerance:
    tth: [0.25, 0.20]
    eta: [3.0, 2.0]
    omega: [2.0, 1.0]

  refit: [2, 1]

  # true, false, or a non-negative value, defaults to true
  tth_max: false 
```

Once the options are set and the dialog is accepted, they should be saved in
`HexrdConfig().indexing_config['fit_grains']`, and [the config that is created here](https://github.com/HEXRD/hexrdgui/blob/1556de632910c2ace7c27ff06933e2f0143aa999/hexrd/ui/indexing/run.py#L112)
will automatically have them set inside it.

It is valuable for the dialogs to be non-blocking (`dialog.show()`) instead of blocking (`dialog.exec_()`) because the user might want to look at the main image canvas when choosing some of the options.

Some of the explanations of the things going on can be found in [this YouTube video](https://www.youtube.com/watch?v=I6gJqoB5V3U&t=241s).
